### ISSUE TITLE
MM cache is not compatible with \n

### ISSUE THREAD

**Issue by Sigma88** [sarbian/ModuleManager#84] opened 2017-10-25 10:25 UTC
example:

```
NODE
{
    description = FirstLine\nSecondLine
}
```
will be saved to the cache as

```
UrlConfig
{
    name = NODE
    type = NODE
    parentUrl = /test
    url = /test/NODE
    NODE
    {
        description = FirstLine
SecondLine
    }
}
```

which means that when running KSP without MM cache the description will be loaded as

``FirstLine\nSecondLine``

while when running KSP and loading the nodes from the MM cache, the description will be loaded as just

``FirstLine``

**Comment by Sigma88** [comment] 2017-10-25 10:40
pinging @blowfishpro in case he might know :)

**Comment by sarbian** [comment] 2017-10-25 11:39
The cache is written with KSP stock ConfigNode.Save(path) so the problem is in there :(
So we either have to escape everything before saving, write our own Save or cache in an other format (binary serialization ? protobuf ?). That may improve perf a bit more. Or not.

**Comment by Sigma88** [comment] 2017-10-25 12:06
in the meantime I've circumvented the issue using ``&br;`` and ``.Replace("&br;","\n")``

let me know if you need some tests

**Comment by blowfishpro** [comment] 2017-10-25 18:24
Sounds like KSP is handling escaping properly when loading but not when saving.  I'll see about letting Squad know about this

**Comment by Sigma88** [comment] 2017-10-25 19:28
the major problem about this is that the behaviour is not consistent between starts

if you start the game without the cache the result is different than with the cache.

if it wasn't for that I wouldn't have even noticed

**Comment by blowfishpro** [comment] 2017-10-26 05:44
Interesting, apparently `\n` is only properly processed in the first place because of the localizer.  So I guess that explains why it's not handled on save

**Comment by jrossignol** [comment] 2018-03-25 15:40
Ugh, I hit this one too.  Used to work before 1.3 because KSP wouldn't do anything with the \n.

**Comment by Sigma88** [comment] 2018-03-25 16:11
I haven't closed the issue just because the info might help people having this same issue, just make sure you use an alternative symbol (I use `&br;`)

**Comment by jrossignol** [comment] 2018-03-25 16:19
The problem with changing to `&br;` is that I can't easily assess the impact - out of two dozen or so contract packs out there, they could all be using '\n' voraciously...  or not using it at all.  So I'd rather explore options that don't require that change until I have no other choice.

**Comment by Sigma88** [comment] 2018-03-25 16:29
ah yes, but the issue here (iirc) is that the localizer changes \n to *newline* so by the time mm gets the cfg it is already messed up

@sarbian  @blowfishpro  correct me if I'm wrong

**Comment by blowfishpro** [comment] 2018-03-25 19:08
That's correct.  The only thing I can think of to fix this on MM's side would be to rewrite the ConfigNode saving code and use that when writing the cache.

**Comment by jrossignol** [comment] 2018-03-25 20:32
Agreed, it's not pretty, and even if it was I'm not sure if I'd want to be the one to have MM reformat *every* config node value before it goes the door in cache.

So @JPLRepo - since I can't easily ping you on the KSP tracker, any chance you (or someone else) can respond on [#16315](https://bugs.kerbalspaceprogram.com/issues/16315) to let us know if there's any chance for a fix in 1.4.2?

**Comment by JPLRepo** [comment] 2018-03-25 21:14
You can always get me on IRC.

**Comment by seanth** [comment] 2018-05-24 16:46
In some experiments with Kopernicus today, I was able to get line feeds using a syntax like "\\nn""

The internal "\n" is removed, but in doing so, it creates a valid "\n". I tested this using MM cache or fresh, and both worked in my hands.

Not a great solution, but could be a workaround.

**Comment by blowfishpro** [comment] 2019-08-06 23:26
Fixed now

**Closed by blowfishpro** 2019-08-06 23:26 UTC

**Comment by Sigma88** [comment] 2019-08-07 09:15
Thanks @blowfish this is great!
